### PR TITLE
ci: archive sample app

### PR DESCRIPTION
**Pull request by imaginaris**
# Description
Added archiving sample app as a part of CI pipeline.
The archive will be exported to Bitrise on every build.

# Checklist
- [X] I have read the [contributing guidelines](../CONTRIBUTING.md).
- [ ] I wrote/updated tests for new/changed code
- [X] I removed all sensitive data **before every commit**, including API endpoints and keys
- [X] I ran `fastlane ci` without errors

### CODE REVIEW

**Review by donnie-jp — APPROVED** [review]
🎉

**Comment by donnie-jp** [comment]
@imaginaris Will this include the dSYMs in the xcarchive automatically?

**Review by malayli — APPROVED** [review]

**Comment by imaginaris** [comment]
> @imaginaris Will this include the dSYMs in the xcarchive automatically?

Yes it will

**Comment by imaginaris** [comment]
> @imaginaris Will this include the dSYMs in the xcarchive automatically?

Example artifact:
https://app.bitrise.io/build/12f98c17-abae-43dc-882a-b117cbc8bdcf?tab=artifacts

**Review by apparition47 — APPROVED** [review]

**Pull request merged**
